name: Publish to Nuget

on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Build and publish
        run: |
          dotnet pack -o output src/DotnetVersion/DotnetVersion.csproj
          dotnet nuget push output/ -s https://nuget.org -k ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
